+incdir+${VPU_HOME}/design/sverilog

${VPU_HOME}/design/sverilog/VPU_TOP.sv
${VPU_HOME}/design/sverilog/VPU_TOP_WRAPPER.sv
${VPU_HOME}/design/sverilog/VPU_TOP_XLINX_WRAPPER.v
${VPU_HOME}/design/sverilog/VPU_SRC_PORT.sv
${VPU_HOME}/design/sverilog/VPU_SRC_PORT_CONTROLLER.sv
${VPU_HOME}/design/sverilog/VPU_REDUCTION_UNIT.sv
${VPU_HOME}/design/sverilog/VPU_PKG.svh
${VPU_HOME}/design/sverilog/VPU_LANE.sv
${VPU_HOME}/design/sverilog/VPU_IF.sv
${VPU_HOME}/design/sverilog/VPU_FP_SQRT.sv
${VPU_HOME}/design/sverilog/VPU_FP_MUL.sv
${VPU_HOME}/design/sverilog/VPU_FP_MAX2.sv
${VPU_HOME}/design/sverilog/VPU_FP_MAX3.sv
${VPU_HOME}/design/sverilog/VPU_FP_DIV.sv
${VPU_HOME}/design/sverilog/VPU_FP_AVG2.sv
${VPU_HOME}/design/sverilog/VPU_FP_AVG3.sv
${VPU_HOME}/design/sverilog/VPU_FP_EXP.sv
${VPU_HOME}/design/sverilog/VPU_FP_RECIP.sv
${VPU_HOME}/design/sverilog/VPU_FP_ADD2.sv
${VPU_HOME}/design/sverilog/VPU_FP_ADD3.sv
${VPU_HOME}/design/sverilog/VPU_EXEC_UNIT.sv
${VPU_HOME}/design/sverilog/VPU_DECODER.sv
${VPU_HOME}/design/sverilog/VPU_CONTROLLER.sv
${VPU_HOME}/design/sverilog/VPU_WB_UNIT.sv