+incdir+${CMSS_HOME}/design/sverilog
${VPU_HOME}/design/sverilog/VPU_TOP.sv
${VPU_HOME}/design/sverilog/VPU_TOP_WRAPPER.sv
${VPU_HOME}/design/sverilog/VPU_SRC_PORT.sv
${VPU_HOME}/design/sverilog/VPU_SRC_PORT_CONTROLLER.sv
${VPU_HOME}/design/sverilog/VPU_REDUCTION_UNIT.sv
${VPU_HOME}/design/sverilog/VPU_PKG.svh
${VPU_HOME}/design/sverilog/VPU_LANE.sv
${VPU_HOME}/design/sverilog/VPU_IF.sv
${VPU_HOME}/design/sverilog/VPU_FP_SQRT.sv
${VPU_HOME}/design/sverilog/VPU_FP_MUL.sv
${VPU_HOME}/design/sverilog/VPU_FP_MAX.sv
${VPU_HOME}/design/sverilog/VPU_FP_DIV.sv
${VPU_HOME}/design/sverilog/VPU_FP_AVG.sv
${VPU_HOME}/design/sverilog/VPU_FP_ADD_SUB.sv
${VPU_HOME}/design/sverilog/VPU_EXEC_UNIT.sv
${VPU_HOME}/design/sverilog/VPU_DECODER.sv
${VPU_HOME}/design/sverilog/VPU_CONTROLLER.sv
${VPU_HOME}/design/sverilog/VPU_CNTR.sv
${VPU_HOME}/design/sverilog/VPU_WB_UNIT.sv

${VPU_HOME}/design/xilinx_ip/floating_point_add_sub.xci
${VPU_HOME}/design/xilinx_ip/floating_point_cmp.xci
${VPU_HOME}/design/xilinx_ip/floating_point_div.xci
${VPU_HOME}/design/xilinx_ip/floating_point_exp.xci
${VPU_HOME}/design/xilinx_ip/floating_point_mul.xci
${VPU_HOME}/design/xilinx_ip/floating_point_sqrt.xci