# This file describes a workflow that runs synthesis
# on a pull request to the main branch
name: Synthesis-Vivado
run-name: Run Vivado Synthesis (Xilinx) from ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 5 * * *'    # 5:30 AM (UTC), any day of the month, any month, any day of the week
  workflow_dispatch:

jobs:
  Vivado:
    runs-on: self-hosted        # runs on a server with Xilinx Vivado installed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Synthesis
        run: |
          source ${{github.workspace}}/env.source ${{github.workspace}}
          ${{github.workspace}}/actions/action.syn_vivado
        env:
          CMSS_HOME: ${{github.workspace}}
          ACTION_HOME: ${{github.workspace}}/actions
          DESIGN_TOP: CMSS_TOP_WRAPPER2